# 설정 변수들 저장 파일.

px_per_m_x: 190
px_per_m_y: 190
scan_interval: 0.2
filter_window: 5
k_neighbors: 3
map_file: "map.png"

rooms:
  - name: 101호
    x: 2.53  # 481 / 20
    y: 2.51  # 477 / 20
  - name: 102호
    x: 2.53  # 473 / 20
    y: 0.57    # 110 / 20
  - name: 103호
    x: 1.52   # 290 / 20
    y: 0.57    # 110 / 20

beacon_macs:
  - "C3:00:00:44:DC:1A"
  - "C3:00:00:44:DC:1B"
  - "C3:00:00:44:DC:1C"
  - "C3:00:00:44:DC:1D"
  - "C3:00:00:44:DC:1E"
  - "C3:00:00:44:DC:1F"